import { useEffect, useState } from "react";
import JournalsCSS from "../../styles/components/index/journals.module.css";

import Journal from "./journal";

const Journals = () => {
    let [templateArray, setTemplateArray] = useState([]);

    useEffect(() => {
        setTemplateArray([
            {
                bannerImage: "https://images.unsplash.com/photo-1642707178674-c390921418d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwxfDB8MXxyYW5kb218MHx8fHx8fHx8MTY0Mjk4MjI3Mg&ixlib=rb-1.2.1&q=80&w=1080",
                title: "랜덤생성된 타이틀",
                subtitle: "Generated by GAN",
                author: "GAN"
            }
        ])
    });
   
    return (
        <div className={JournalsCSS.Journals}>
            <div className={JournalsCSS.HeaderWrapper}>
                <div className={JournalsCSS.Header}>
                    Journals
                </div>
            </div>
            <div className={JournalsCSS.JournalGrid}>
                {
                    templateArray.map(
                        (template, ind) => (
                            <Journal
                                bannerImage={template.bannerImage}
                                title={template.title}
                                subtitle={template.subtitle}
                                author={template.author}
                            />
                        )
                    )
                }
            </div>
        </div>
    )
}

export default Journals;